switch:
  - platform: sigen_smartport
      name: "Sigen Smart Port Control"
      #unique_id: "sigen_smart_port_main_switch"
      username: "username@xxx.com"
      password: "encryptedFromDeveloperTools" 
      station_id: "stationIdFromDeveloperTools"
      load_path: "1"
      auth_header: "Basic xxxxxxxxxxx"
      user_device_id: "devideID"
select:
  - platform: sigen_smartport
    name: "Sigen Smart Port Mode"
    username: "username@xxx.com"
    password: "encryptedFromDeveloperTools" 
    station_id: "stationIdFromDeveloperTools"
    load_path: "1"
    auth_header: "Basic xxxxxxxxxxx"
    user_device_id: "devideID"
